feature/CU-jv46ze_FRONT-END-Create-home-page
Horsemen-and-Women-of-the-Apocalypse/quiz-frontend pull request #3
Opened 2021-05-15 16:11 UTC by Thurstag

2021-05-15 16:11 UTC, Thurstag commented
Task linked: [CU-jv46ze [FRONT-END] Create home page](https://app.clickup.com/t/jv46ze)

2021-05-15 16:12 UTC, Thurstag commented
![image](https://user-images.githubusercontent.com/28012414/118370663-09982b00-b5a9-11eb-8843-3cf924e59929.png)

2021-05-16 14:12 UTC, Fantorem requested changes

2021-05-16 14:12 UTC, Fantorem commented on lib/pages/home.dart
> +const String LOBBY_JOINING_BUTTON_TEXT = 'JOIN A LOBBY';
Ce serait peut être mieux de définir un fichier pour l'ensemble des chaînes de l'application (via une classe ou un json).

2021-05-16 14:12 UTC, Fantorem commented on lib/pages/home.dart
> +    return Center(
Le plus souvent on place un "Scaffold" en return (le Center en body du Scaffold ducoup) , pour la gestion de plusieurs composants (pas forcément utile ici) mais aussi pour le responsive.

2021-05-16 14:12 UTC, Fantorem commented on lib/pages/home.dart
> +          paddingBetweenButtons,
Pour faire des Padding tu as un composant : https://api.flutter.dev/flutter/widgets/Padding-class.html

2021-05-16 14:45 UTC, Fantorem approved these changes

2021-05-16 21:17 UTC, furtivesock approved these changes
Peut-être renommer le bouton _Solo_ en _Solo mode_ mais c'est un détail
(coucou je teste l'approbation de PR)

2021-05-17 08:07 UTC, Tomansion approved these changes

2021-05-17 11:40 UTC, merged