feature/CU-jv46zk_FRONT-END-Create-quiz-selection-page
Horsemen-and-Women-of-the-Apocalypse/quiz-frontend pull request #4
Opened 2021-05-16 20:18 UTC by Thurstag

2021-05-16 20:18 UTC, Thurstag commented
Task linked: [CU-jv46zk [FRONT-END] Create quiz selection page](https://app.clickup.com/t/jv46zk)

2021-05-16 20:19 UTC, Thurstag commented
L'API est pas encore faite donc j'ai pas pu tester la récupération des données

2021-05-16 20:40 UTC, Thurstag commented
Chargement:
![image](https://user-images.githubusercontent.com/28012414/118411968-9faa7f00-b697-11eb-8064-086c02825e0a.png)
Erreur:
![image](https://user-images.githubusercontent.com/28012414/118411974-a933e700-b697-11eb-89d8-a90f845dd8df.png)

2021-05-16 20:57 UTC, Fantorem requested changes

2021-05-16 20:57 UTC, Fantorem commented on lib/widgets/quiz_dropdown_button.dart
> +        future: _quizzesFuture);
Pour la lisibilité c'est mieux de mettre cette ligne avant le builder.

2021-05-16 20:57 UTC, Fantorem commented on lib/pages/solo/quiz_selection.dart
> +    var dropdown = QuizDropdownButton();
Si la variable est utilisé seulement 1 fois, place directement `QuizDropdownButton()` dans `child:`

2021-05-16 20:57 UTC, Fantorem commented on lib/pages/solo/quiz_selection.dart
> +            Padding(padding: EdgeInsets.only(bottom: padding), child: dropdown),
ici

2021-05-16 21:04 UTC, Thurstag commented on lib/widgets/quiz_dropdown_button.dart
> +        future: _quizzesFuture);
Ouais mais Android Studio fait pas chier avec l'ordonnancement des paramètres ?

2021-05-16 21:04 UTC, Thurstag commented on lib/pages/solo/quiz_selection.dart
> +    var dropdown = QuizDropdownButton();
On va avoir besoin du widget dans la callback pour récupérer le quiz sélectionné donc c'est pour ça qu'il y a une variable

2021-05-17 08:08 UTC, Tomansion approved these changes

2021-05-17 14:16 UTC, YesLife approved these changes

2021-05-17 14:59 UTC, LeBoyLeoz approved these changes

2021-05-17 21:18 UTC, Fantorem commented on lib/widgets/quiz_dropdown_button.dart
> +        future: _quizzesFuture);
Normalement non mais c'est pas une modif importante.

2021-05-19 19:34 UTC, Fantorem approved these changes

2021-05-19 19:36 UTC, Tomansion approved these changes

2021-05-19 19:46 UTC, merged